import blueEyesWhiteDragon from "@assets/Monsters/blue-eyes-white-dragon.jpg";
import darkMagician from "@assets/Monsters/dark-magician.jpg";
// import backImage from "@assets/back.png";

export const INITIAL_CARDS: CardData[] = [
  {
    id: 1,
    playerId: 1,
    name: "Dark Magician",
    image: darkMagician,
    status: "inDeck",
    attack: 2500,
    defense: 2100,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 2,
    playerId: 1,
    name: "Blue-Eyes White Dragon",
    image: blueEyesWhiteDragon,
    status: "inDeck",
    attack: 3000,
    defense: 2500,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 3,
    playerId: 1,
    name: "Dark Magician",
    image: darkMagician,
    status: "inDeck",
    attack: 2500,
    defense: 2100,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 4,
    playerId: 1,
    name: "Blue-Eyes White Dragon",
    image: blueEyesWhiteDragon,
    status: "inDeck",
    attack: 3000,
    defense: 2500,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 5,
    playerId: 1,
    name: "Dark Magician",
    image: darkMagician,
    status: "inDeck",
    attack: 2500,
    defense: 2100,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 6,
    playerId: 1,
    name: "Blue-Eyes White Dragon",
    image: blueEyesWhiteDragon,
    status: "inDeck",
    attack: 3000,
    defense: 2500,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 7,
    playerId: 1,
    name: "Dark Magician",
    image: darkMagician,
    status: "inDeck",
    attack: 2500,
    defense: 2100,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
];

export const OPPONENT_INITIAL_CARDS: CardData[] = [
  {
    id: 8,
    playerId: 2,
    name: "Dark Magician",
    image: darkMagician,
    status: "inDeck",
    attack: 2500,
    defense: 2100,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 9,
    playerId: 2,
    name: "Blue-Eyes White Dragon",
    image: blueEyesWhiteDragon,
    status: "inDeck",
    attack: 3000,
    defense: 2500,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 10,
    playerId: 2,
    name: "Dark Magician",
    image: darkMagician,
    status: "inDeck",
    attack: 2500,
    defense: 2100,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 11,
    playerId: 2,
    name: "Blue-Eyes White Dragon",
    image: blueEyesWhiteDragon,
    status: "inDeck",
    attack: 3000,
    defense: 2500,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 12,
    playerId: 2,
    name: "Dark Magician",
    image: darkMagician,
    status: "inDeck",
    attack: 2500,
    defense: 2100,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 13,
    playerId: 1,
    name: "Blue-Eyes White Dragon",
    image: blueEyesWhiteDragon,
    status: "inDeck",
    attack: 3000,
    defense: 2500,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
  {
    id: 14,
    playerId: 1,
    name: "Dark Magician",
    image: darkMagician,
    status: "inDeck",
    attack: 2500,
    defense: 2100,
    level: 7,
    description: "Lorem Ipsum",
    type: "Monster",
    position: null,
  },
];

export const INITIAL_GAME_CARDS = {
  player1: INITIAL_CARDS,
  player2: OPPONENT_INITIAL_CARDS,
};
